### ISSUE TITLE
nothing happens when importing mask_example

### ISSUE THREAD

**Issue by blueamerican** [CPS-IT/TYPO3-mask_export#11] opened 2016-08-20 05:10 UTC
hi,

TYPO3 7.6.10
mask 2.0.1

when exporting a configuration named mask_example and installing it in a new project with mask already installed (both static templates mask and mask_example included), nothing happens.

i do not find my fce's or anything in the new project

**Comment by IchHabRecht** [comment] 2016-08-25 08:19
Hi,

Thanks for your feedback. Let me just explain that you don't need to install/use mask when you want to use the export. That is why the export exists.

To understand your problem, would you please attach either your mask.json file and/or the example extension.

**Comment by IchHabRecht** [comment] 2016-11-11 14:59
I okay I see. The problem is still with existing composer.json the information would be missing as long as you just upload the extension ;-)

**Comment by IchHabRecht** [comment] 2016-12-06 23:28
As there was no reaction, I'm closing this issue. Please feel free to open a new request.

**Closed by IchHabRecht** 2016-12-06 23:28 UTC
Labels: feedback
